export const GET_BREEDS = 'GET_BREEDS';
export const GET_BREED_NAME = 'GET_BREED_NAME';
export const GET_BREED_ID = 'GET_BREED_ID';
export const POST_BREED = 'POST_BREED';
export const GET_TEMPERAMENT = 'GET_TEMPERAMENT';
export const SET_LOADING = 'SET_LOADING';

export const COPY_STATE = 'COPY_STATE';
export const FILTER_TEMPERAMENTS = 'FILTER_TEMPERAMENTS';
export const FILTER_ORDER_NAME = 'FILTER_ORDER_NAME';
export const FILTER_ORDER_WEIGHT = 'FILTER_ORDER_WEIGHT';
export const FILTER_NAME = 'FILTER_NAME';
export const FILTER_DATA = 'FILTER_DATA';