export const GET_BREEDS = 'GET_BREEDS';
export const GET_BREED_NAME = 'GET_BREED_NAME';
export const GET_BREED_ID = 'GET_BREED_ID';
export const POST_BREED = 'POST_BREED';
export const GET_TEMPERAMENT = 'GET_TEMPERAMENT';

export const FILTER_TEMPERAMENTS = 'FILTER_TEMPERAMENTS';
export const FILTER_NAME_ASC = 'FILTER_NAME_ASC';
export const FILTER_NAME_DESC = 'FILTER_NAME_DESC';
export const FILTER_WEIGHT_ASC = 'FILTER_WEIGHT_ASC';
export const FILTER_WEIGHT_DESC = 'FILTER_WEIGHT_DESC';